### ISSUE TITLE
[14.0] error with traceback when syncing sendcloud objects via API and Returns enabled

### ISSUE THREAD

**Issue by janbec** [onesteinbv/addons-sendcloud#12]
## Steps to reproduce
* Use the odoo API integration
* Go to configuration ->Sync the sendcloud objects
* On the opening wizard, make sure the option returns is enabled
* press sync

## Traceback (shortened)
```
Fehler:
Odoo Server Error

Traceback (most recent call last):

  File "/addons/delivery_sendcloud_official/wizards/sendcloud_sync_wizard.py", line 31, in button_sync
    self.env["sendcloud.return"].sendcloud_sync_returns()
  File "/addons/delivery_sendcloud_official/models/sendcloud_return.py", line 209, in sendcloud_sync_returns
    self.sendcloud_create_or_update_returns(return_data, company)
  File "/addons/delivery_sendcloud_official/models/sendcloud_return.py", line 196, in sendcloud_create_or_update_returns
    new_created_records = self.create(vals_list)

Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/build/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/build/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Wrong value for sendcloud.return.delivery_option: 'drop_off_labelless'
```

## Resolution
Our sendcloud module works without syncing the returns. If you disable the option, the syncing will work.
If you add the `drop_off_labelless `option to the `delivery_option` Selection field in sendcloud_return.py, the error disappears.
![grafik](https://user-images.githubusercontent.com/28890800/148282661-bb1b9e09-f1f7-40af-901d-d3f35cd30918.png)

**Comment by tarteo** [comment]
Thanks again :smile: , it's fixed now
