### ISSUE TITLE
Can't confirm sales orders with Sendcloud shipping added

### ISSUE THREAD

**Issue by steenbergentim** [onesteinbv/addons-sendcloud#15]
Hi,

I can not confirm a sales order. The problem only occurs when I add a Sendcloud shipping method to the particular sales order. I have all the Sendcloud objects synchronised and the two warehouses seem to be correctly setup. Any idea why this happens?

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1352, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1340, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/website_sale/models/sale_order.py", line 366, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "/home/odoo/src/odoo/addons/sale_management/models/sale_order.py", line 153, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "/home/odoo/src/odoo/addons/sale/models/sale_order.py", line 990, in action_confirm
    self.with_context(context)._action_confirm()
  File "/home/odoo/src/user/delivery_sendcloud_official/models/sale_order.py", line 117, in _action_confirm
    to_sync._sync_picking_to_sendcloud()
  File "/home/odoo/src/user/delivery_sendcloud_official/models/stock_picking.py", line 572, in _sync_picking_to_sendcloud
    err_msg = self._sync_shipment_to_sendcloud(err_msg, integration, vals)
  File "/home/odoo/src/user/delivery_sendcloud_official/models/stock_picking.py", line 602, in _sync_shipment_to_sendcloud
    status = confirmation.get("status")
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'str' object has no attribute 'get'

**Comment by tarteo** [comment]
What is the content of `confirmation`? I can't reproduce it.

Same issue here: https://github.com/onesteinbv/addons-sendcloud/issues/8

Which version are you using?

**Comment by steenbergentim** [comment]
Hi Dennis,
I am not sure if I understand your question, but my meaning of confirmation is that I am trying to confirm a quotations so it becomes a sales order. Is that the answer to your question?

I am using Odoo 15 Enterprise via Odoo.sh.

Thanks for replying so quickly.

**Comment by tarteo** [comment]
Thanks, if you're able to debug the code can you lookup what `confirmation` contains? I think it's a network issue from your or Sendcloud side. 

Do you still get an error now when you try to confirm a quotation?
