### ISSUE TITLE
Creating Shipping Label results in ValueError: Wrong value for sendcloud.parcel.sendcloud_status: '1000'

### ISSUE THREAD

**Issue by lillebutik** [onesteinbv/addons-sendcloud#4]
Any suggestions to how I can debug this issue?

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/odoo-14ee/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14/odoo-14ee/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14/odoo-14ee/odoo/addons/stock_sms/wizard/confirm_stock_sms.py", line 19, in send_sms
    return pickings_to_validate.button_validate()
  File "/opt/odoo14/odoo-14ee/odoo/addons/stock/models/stock_picking.py", line 942, in button_validate
    pickings_to_backorder.with_context(cancel_backorder=False)._action_done()
  File "/opt/odoo14/odoo-14ee/odoo/addons/sale_stock/models/stock.py", line 76, in _action_done
    res = super()._action_done()
  File "/opt/odoo14/odoo-14ee/odoo/addons/stock/models/stock_picking.py", line 770, in _action_done
    self._send_confirmation_email()
  File "/opt/odoo14/odoo-14ee/odoo/addons/delivery/models/stock_picking.py", line 129, in _send_confirmation_email
    pick.send_to_shipper()
  File "/opt/odoo14/odoo-14ee/odoo/addons/delivery/models/stock_picking.py", line 170, in send_to_shipper
    res = self.carrier_id.send_shipping(self)[0]
  File "/opt/odoo14/odoo-14ee/odoo/addons/delivery/models/delivery_carrier.py", line 174, in send_shipping
    return getattr(self, '%s_send_shipping' % self.delivery_type)(pickings)
  File "/opt/odoo14/odoo-custom-addons/delivery_sendcloud_official/models/delivery_carrier.py", line 118, in sendcloud_send_shipping
    res = pickings._sendcloud_send_shipping()
  File "/opt/odoo14/odoo-custom-addons/delivery_sendcloud_official/models/stock_picking.py", line 589, in _sendcloud_send_shipping
    self._sendcloud_create_update_received_parcels(
  File "/opt/odoo14/odoo-custom-addons/delivery_sendcloud_official/models/stock_picking.py", line 683, in _sendcloud_create_update_received_parcels
    res += self.env["sendcloud.parcel"].create(odoo_parcels_vals)
  File "<decorator-gen-132>", line 2, in create
  File "/opt/odoo14/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo14/odoo-14ee/odoo/addons/mail/models/mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/opt/odoo14/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo14/odoo/odoo/addons/base/models/ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo14/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo14/odoo/odoo/models.py", line 3868, in create
    records = self._create(data_list)
  File "/opt/odoo14/odoo/odoo/models.py", line 3940, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/opt/odoo14/odoo/odoo/fields.py", line 2402, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/opt/odoo14/odoo/odoo/fields.py", line 2414, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Wrong value for sendcloud.parcel.sendcloud_status: '1000'

**Comment by astirpe** [comment]
@lillebutik did you sync the Parcel Statuses?

**Comment by lillebutik** [comment]
The import of parcel status from Sendcloud didnt work the first time. Ran it again and it is fixed.
