### ISSUE TITLE
[15.0] return value is expected to be a dict, but str is returned

### ISSUE THREAD

**Issue by wtaferner** [onesteinbv/addons-sendcloud#8]
Hope this helps to eliminate this issue straight forward.

Seems like there is a traceback while confirming an order related to a mixture of return values...

```python
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1339, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/printnode_base/controllers/main.py", line 49, in _call_kw
    return super(DataSetProxy, self)._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1327, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/printnode_base/models/sale_order.py", line 12, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "/opt/odoo/auto/addons/sale_crm/models/sale_order.py", line 15, in action_confirm
    return super(SaleOrder, self.with_context({k:v for k,v in self._context.items() if k != 'default_tag_ids'})).action_confirm()
  File "/opt/odoo/auto/addons/website_sale/models/sale_order.py", line 366, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "/opt/odoo/auto/addons/sale_management/models/sale_order.py", line 153, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "/opt/odoo/auto/addons/sale/models/sale_order.py", line 988, in action_confirm
    self.with_context(context)._action_confirm()
  File "/opt/odoo/auto/addons/delivery_sendcloud_official/models/sale_order.py", line 117, in _action_confirm
    to_sync._sync_picking_to_sendcloud()
  File "/opt/odoo/auto/addons/delivery_sendcloud_official/models/stock_picking.py", line 569, in _sync_picking_to_sendcloud
    err_msg = self._sync_shipment_to_sendcloud(err_msg, integration, vals)
  File "/opt/odoo/auto/addons/delivery_sendcloud_official/models/stock_picking.py", line 599, in _sync_shipment_to_sendcloud
    status = confirmation.get("status")
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'str' object has no attribute 'get'
```

**Comment by astirpe** [comment]
Thank you @wtaferner, do you have the possibility to debug to see what `confirmation` contains?

**Comment by wtaferner** [comment]
Unfortunately, not yet, but I thought maybe you directly know what went wrong or maybe what was missed during migration to 15.0?
In case you guys can not reproduce it and do not see the obvious reason, I will probably need to fix it myself and report back or contribute with a PR.

**Comment by tarteo** [comment]
@wtaferner I can't reproduce this error. Does this happen everytime, or just sometimes. Can you describe in more detail what you're doing or even better debug what's the value of `confirmation` / `response`.
![image](https://user-images.githubusercontent.com/10028499/146000024-f2ffd002-57d0-4036-9ab7-95974a2f3ad7.png)

**Comment by wtaferner** [comment]
@tarteo 
So, I was not able to reproduce it either, so I can not give any further hints, but I guess it would help to check the type and make it a bit more waterproof for the error handling...so far, so good, thank you for taking care of the issue.

I close the issue as it is not clearly reproducible even though it is clear from the traceback that it happened for whatever reason 😉
